ALTER TABLE `shaly_sands`.`mojave_federal44f` 
CHANGE COLUMN `Depth` `Depth` DOUBLE NOT NULL COMMENT 'in ft' ,
CHANGE COLUMN `Res10IN` `Res10IN` DOUBLE NOT NULL COMMENT 'DOI 10inch - Extra shallow in ohm-m' ,
CHANGE COLUMN `Res20IN` `Res20IN` DOUBLE NOT NULL COMMENT 'DOI 20inch - shallow in ohm-m' ,
CHANGE COLUMN `Res30IN` `Res30IN` DOUBLE NOT NULL COMMENT 'DOI 30inch - Medium in ohm-m' ,
CHANGE COLUMN `Res60IN` `Res60IN` DOUBLE NOT NULL COMMENT 'DOI 60inch - in ohm-m' ,
CHANGE COLUMN `Res90IN` `Res90IN` DOUBLE NOT NULL COMMENT 'DOI 90inch - Deep Resistivity in ohm-m' ,
CHANGE COLUMN `A5DBHC` `A5DBHC` DOUBLE NOT NULL COMMENT 'mmho/m (conductivity)' ,
CHANGE COLUMN `ABHV` `ABHV` DOUBLE NOT NULL COMMENT 'Annular Volume ft3' ,
CHANGE COLUMN `CNLS` `CNLS` DOUBLE NOT NULL COMMENT 'Limestone - CN porosity' ,
CHANGE COLUMN `CNPOR` `CNPOR` DOUBLE NOT NULL COMMENT 'Selected CN porosity' ,
CHANGE COLUMN `DBHC` `DBHC` DOUBLE NOT NULL COMMENT 'Density Borehole Correction g/cc' ,
CHANGE COLUMN `DCAL` `DCAL` DOUBLE NOT NULL COMMENT 'Density Caliper in inches' ,
CHANGE COLUMN `DFCAL` `DFCAL` DOUBLE NOT NULL COMMENT 'Differential Caliper in inches' ,
CHANGE COLUMN `DPHI` `DPHI` DOUBLE NOT NULL COMMENT 'Density Porosity v/v - limestone matrix' ,
CHANGE COLUMN `DPHIL` `DPHIL` DOUBLE NOT NULL COMMENT 'Density Porosity from RHOLS v/v' ,
CHANGE COLUMN `DRHO` `DRHO` DOUBLE NOT NULL COMMENT 'Density Correction g/cc' ,
CHANGE COLUMN `GR` `GR` DOUBLE NOT NULL COMMENT 'Gamma Ray °API' ,
CHANGE COLUMN `GRTEMP` `GRTEMP` DOUBLE NOT NULL COMMENT 'Gamma Ray sensor Temperature °F' ,
CHANGE COLUMN `MudR` `MudR` DOUBLE NOT NULL COMMENT 'Mud Resistivity ohm-m' ,
CHANGE COLUMN `PEF` `PEF` DOUBLE NOT NULL COMMENT 'Photo-electric Factor banrs/e' ,
CHANGE COLUMN `RHOB` `RHOB` DOUBLE NOT NULL COMMENT 'Bulk Density g/cc' ,
CHANGE COLUMN `TBHV` `TBHV` DOUBLE NOT NULL COMMENT 'Borehole Volume ft3' ,
CHANGE COLUMN `CNPORVV` `CNPORVV` DOUBLE NOT NULL COMMENT 'CN Selected Porosity Expressed as Decimal' ,
CHANGE COLUMN `DPHIVV` `DPHIVV` DOUBLE NOT NULL COMMENT 'Density Porosity Expressed as Decimal' ,
CHANGE COLUMN `CNLSVV` `CNLSVV` DOUBLE NOT NULL COMMENT 'CN Limestone Porosity Expressed as Decimal v/v' ,
CHANGE COLUMN `DPHILVV` `DPHILVV` DOUBLE NOT NULL COMMENT 'Density Porosity from RHOLS Expressed as Decimal v/v' ,
CHANGE COLUMN `V_sh_raw` `V_sh_raw` DOUBLE NOT NULL COMMENT 'Gamma Ray Index / Raw Shale content' ,
CHANGE COLUMN `V_sh_corr` `V_sh_corr` DOUBLE NOT NULL COMMENT 'Clavier\'s Corrected Shale Content- Vsh' ,
CHANGE COLUMN `CNSS` `CNSS` DOUBLE NOT NULL COMMENT 'Sandstone -  CN porosity' ,
CHANGE COLUMN `DPHI_SS` `DPHI_SS` DOUBLE NOT NULL COMMENT 'Sandstone - Density Porisity' ,
CHANGE COLUMN `DPHI_Corr` `DPHI_Corr` DOUBLE NOT NULL COMMENT 'Shale Corrected Density Porosity v/v' ,
CHANGE COLUMN `NPHI_Corr` `NPHI_Corr` DOUBLE NOT NULL COMMENT 'Shale Corrected CN porosity v/v' ,
CHANGE COLUMN `PHI_e` `PHI_e` DOUBLE NOT NULL COMMENT 'Effective Porosity in decimal' ,
ADD PRIMARY KEY (`Depth`);
;
